### ISSUE TITLE
KeyError: 'conv1.lin.weight'

### ISSUE THREAD

**Issue by Jeratt** [funket/zorro#1]
I tried to run "execution.py" and got this error. How it could be fixed? Also, "execution.py" has "APPNP10Net": APPNP10Net" in model_classes, this thing raise NameError, because of APPNP10Net and the entire project does not have this model in other places

All requirements was satisfied but these errors occur with more up-to-date library versions too. 

![image](https://user-images.githubusercontent.com/98951973/181526573-bcc67494-ae8e-4844-b27b-ae86c5dbb635.png)

**Comment by funket** [comment]
Thanks for highlighting the problem with the old reference to "APPNP10Net", which we removed and didn't included in the cleaned repository. I just fixed that bug and updated the repository. 

The issue with the loading I could not reproduce with my python repository, which has exactly the versions installed as stated in requirements.txt. I would assume that this issue is caused by using a newer PyTorch geometric version, which may have slightly altered the structure of the save files. You can either train your own GNNs (which should not take much time) and is automatically triggered, if no save file is found. Alternatively, you can debug which content is stored in the save file and compare the names of the matrices with the ones of a new save file. Afterwards, a small function for renaming the matrices should fix it.
